# Generated by Django 5.1 on 2024-08-09 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flying_piggy_app', '0002_shortcut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsentry',
            name='goal',
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
