# Generated by Django 5.1 on 2024-08-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flying_piggy_app', '0004_alter_savingsentry_options_remove_savingsgoal_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingsentry',
            options={'verbose_name': 'Savings entry', 'verbose_name_plural': 'Savings entries'},
        ),
        migrations.AlterModelOptions(
            name='savingsgoal',
            options={'verbose_name': 'Savings goal', 'verbose_name_plural': 'Savings goals'},
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goal_images/'),
        ),
    ]
