# Generated by Django 5.1 on 2024-08-09 16:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flying_piggy_app', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
